## **Title:** Building a Disease Diagnosis and Prescription Recommendation System with Machine Learning  

**Description:**  
Explore our advanced Personalized Medical Recommendation System, powered by machine learning. This innovative platform analyzes symptoms to accurately predict potential diseases, helping users better understand and manage their health.

# 1. load the dataset

In [40]:
import  pandas as pd
dataset = pd.read_csv('datasets/Training.csv')
print(dataset.shape)
print(dataset.head())

(4920, 133)
   itching  skin_rash  nodal_skin_eruptions  continuous_sneezing  shivering  \
0        1          1                     1                    0          0   
1        0          1                     1                    0          0   
2        1          0                     1                    0          0   
3        1          1                     0                    0          0   
4        1          1                     1                    0          0   

   chills  joint_pain  stomach_pain  acidity  ulcers_on_tongue  ...  \
0       0           0             0        0                 0  ...   
1       0           0             0        0                 0  ...   
2       0           0             0        0                 0  ...   
3       0           0             0        0                 0  ...   
4       0           0             0        0                 0  ...   

   blackheads  scurring  skin_peeling  silver_like_dusting  \
0           0         0 

# 2. train test split

In [43]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

# Splitting features (X) and target variable (y)
X = dataset.drop('prognosis', axis=1)
y = dataset['prognosis']

# Encoding the 'prognosis' column (target variable)
le = LabelEncoder()
y_encoded = le.fit_transform(y)  # Encode target variable

# Splitting the data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.3, random_state=20)

# 3. Training & Select the best model

In [4]:
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, AdaBoostClassifier, BaggingClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import MultinomialNB, GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import f1_score, confusion_matrix
import numpy as np

# Create a dictionary to store models
models = {
    'SVC': SVC(kernel='linear'),
    'RandomForest': RandomForestClassifier(n_estimators=100, random_state=42),
    'GradientBoosting': GradientBoostingClassifier(n_estimators=100, random_state=42),
    'AdaBoost': AdaBoostClassifier(n_estimators=50, random_state=42),
    'Bagging': BaggingClassifier(n_estimators=10, random_state=42),
    'KNeighbors': KNeighborsClassifier(n_neighbors=5),
    'MultinomialNB': MultinomialNB(),
    'GaussianNB': GaussianNB(),
    'LogisticRegression': LogisticRegression(random_state=42),
    'DecisionTree': DecisionTreeClassifier(random_state=42)
}

# Loop through the models, train, test, and print results
for model_name, model in models.items():
    # Train the model
    model.fit(X_train, y_train)

    # Test the model
    predictions = model.predict(X_test)

    # Calculate F1-score
    f1 = f1_score(y_test, predictions, average='weighted')
    print(f"{model_name} F1-Score: {f1:.2f}")

    # Calculate confusion matrix
    cm = confusion_matrix(y_test, predictions)
    print(f"{model_name} Confusion Matrix:")
    print(np.array2string(cm, separator=', '))

    print("\n" + "="*40 + "\n")

SVC F1-Score: 1.00
SVC Confusion Matrix:
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]


RandomForest F1-Score: 1.00
RandomForest Confusion Matrix:
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]


GradientBoosting F1-Score: 1.00
GradientBoosting Confusion Matrix:
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]




C:\ProgramData\anaconda3\Lib\site-packages\sklearn\ensemble\_weight_boosting.py:527: FutureWarning: The SAMME.R algorithm (the default) is deprecated and will be removed in 1.6. Use the SAMME algorithm to circumvent this warning.
  warnings.warn(


AdaBoost F1-Score: 0.10
AdaBoost Confusion Matrix:
[[0, 0, 0, ..., 0, 0, 0],
 [0, 0, 0, ..., 0, 0, 0],
 [0, 0, 0, ..., 0, 0, 0],
 ...,
 [0, 0, 0, ..., 0, 0, 0],
 [0, 0, 0, ..., 0, 0, 0],
 [0, 0, 0, ..., 0, 0, 0]]


Bagging F1-Score: 1.00
Bagging Confusion Matrix:
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]


KNeighbors F1-Score: 1.00
KNeighbors Confusion Matrix:
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]


MultinomialNB F1-Score: 1.00
MultinomialNB Confusion Matrix:
[[40,  0,  0, ...,  0,  0,  0],
 [ 0, 43,  0, ...,  0,  0,  0],
 [ 0,  0, 28, ...,  0,  0,  0],
 ...,
 [ 0,  0,  0, ..., 34,  0,  0],
 [ 0,  0,  0, ...,  0, 41,  0],
 [ 0,  0,  0, ...,  0,  0, 31]]


GaussianNB F1-Score:

Given the identical F1-scores and confusion matrices for most models (all at 1.00 except for AdaBoost), the decision-making criteria should go beyond simple performance metrics to consider the following factors:

### 1. Model Interpretability:

**Best Choice**: DecisionTree, LogisticRegression
Decision trees are highly interpretable, making it easy to understand feature importance and decision-making paths.
Logistic regression provides insights into feature contributions via coefficients.
### 2. Scalability and Computational Cost:

**Best Choice**: MultinomialNB, GaussianNB, LogisticRegression, KNeighbors
These models tend to have lower computational requirements, especially for large datasets.
### 3. Overfitting Risk:

**Best Choice**: Bagging, RandomForest, GradientBoosting
These ensemble methods are generally more robust to overfitting compared to a single decision tree.
### 4. Data Characteristics and Use Case:

**Sparse or Text Data**: MultinomialNB, LogisticRegression
Continuous Data or Multi-class Settings: GaussianNB, KNeighbors
### 5. Deployment Requirements:

**Best Choice**: LogisticRegression, SVC
Logistic regression and support vector classifiers are straightforward to deploy due to simpler parameter tuning.
Warnings/Issues:

Avoid using AdaBoost due to its poor F1 score (0.10) and the deprecation warning for the SAMME.R algorithm.
### 6. Recommendation:
**Primary Choice**: If interpretability is key, go with Logistic Regression or Decision Tree.

**Secondary Choice**: For scalability and robustness, choose Random Forest or Gradient Boosting.

**Avoid**: AdaBoost, due to its poor performance.

In [49]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score
# Initialize Random Forest Classifier
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)

# Train the model
rf_model.fit(X_train, y_train)

# Make predictions
y_pred = rf_model.predict(X_test)

# Evaluate the model
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nAccuracy:", accuracy_score(y_test, y_pred))
print("F1 Score:", f1_score(y_test, y_pred, average='weighted'))

# Feature Importance (Optional)
feature_importance = pd.DataFrame({
    'Feature': X.columns,
    'Importance': rf_model.feature_importances_
}).sort_values(by='Importance', ascending=False)
print("\nFeature Importances:")
print(feature_importance)

# Save the trained model (Optional)
import joblib
joblib.dump(rf_model, 'models/random_forest_model.joblib')

Confusion Matrix:
[[40  0  0 ...  0  0  0]
 [ 0 43  0 ...  0  0  0]
 [ 0  0 28 ...  0  0  0]
 ...
 [ 0  0  0 ... 34  0  0]
 [ 0  0  0 ...  0 41  0]
 [ 0  0  0 ...  0  0 31]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      1.00      1.00        43
           2       1.00      1.00      1.00        28
           3       1.00      1.00      1.00        46
           4       1.00      1.00      1.00        42
           5       1.00      1.00      1.00        33
           6       1.00      1.00      1.00        33
           7       1.00      1.00      1.00        39
           8       1.00      1.00      1.00        32
           9       1.00      1.00      1.00        49
          10       1.00      1.00      1.00        37
          11       1.00      1.00      1.00        42
          12       1.00      1.00      1.00        41
          13       1.00      1.00      1.00  

['models/random_forest_model.joblib']

In [50]:
# load model
rf = joblib.load('models/random_forest_model.joblib')

In [51]:
# Function to test and display predictions for given indices
def test_model(model, X_test, y_test, test_indices):
    """
    Test and display predictions for specific indices.

    Parameters:
    - model: Trained model for predictions.
    - X_test: Test feature set (pandas DataFrame or NumPy array).
    - y_test: Test labels (pandas Series or NumPy array).
    - test_indices: List of indices to test.

    Returns:
    - None
    """
    for idx in test_indices:
        # Ensure index is valid
        if idx >= len(X_test):
            print(f"Index {idx} is out of range. Skipping.")
            continue
        # Convert X_test[idx] to array to avoid feature name warnings
        X_sample = X_test.iloc[idx].values.reshape(1, -1) if hasattr(X_test, 'iloc') else X_test[idx].reshape(1, -1)
        predicted = model.predict(X_sample)[0]
        actual = y_test[idx]  # Access directly for NumPy arrays
        print(f"Test {idx + 1}:")
        print(f"  Predicted Disease: {predicted}")
        print(f"  Actual Disease: {actual}")
        print("-" * 40)

# Example usage
test_indices_rf = [0, 100]  # Indices to test for Random Forest

print("Random Forest Predictions:")
test_model(rf, X_test, y_test, test_indices_rf)

Random Forest Predictions:
Test 1:
  Predicted Disease: 40
  Actual Disease: 40
----------------------------------------
Test 101:
  Predicted Disease: 39
  Actual Disease: 39
----------------------------------------


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


# 4. Design the Recommendation System

## Load database and use logic for recommendations

In [24]:
%pip install --upgrade scikit-learn

Note: you may need to restart the kernel to use updated packages.


In [52]:
sym_des = pd.read_csv("datasets/symtoms_df.csv")
precautions = pd.read_csv("datasets/precautions_df.csv")
workout = pd.read_csv("datasets/workout_df.csv")
description = pd.read_csv("datasets/description.csv")
medications = pd.read_csv('datasets/medications.csv')
diets = pd.read_csv("datasets/diets.csv")

In [53]:
# Helper Function
def helper(dis, description, precautions, medications, diets, workout):
    try:
        desc = description[description['Disease'] == dis]['Description']
        desc = " ".join(desc.tolist())
        pre = precautions[precautions['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
        pre = pre.values.flatten().tolist()
        med = medications[medications['Disease'] == dis]['Medication'].tolist()
        diet = diets[diets['Disease'] == dis]['Diet'].tolist()
        wrkout = workout[workout['disease'] == dis]['workout'].tolist()
        return desc, pre, med, diet, wrkout
    except Exception as e:
        print(f"Error retrieving details for disease '{dis}': {e}")
        return None, None, None, None, None

# Prediction Function
def get_predicted_disease(patient_symptoms, symptoms_dict, diseases_list, model, X_train=None):
    """
    Predict the disease based on patient symptoms using the trained model.

    Parameters:
    - patient_symptoms: List of symptoms provided by the patient.
    - symptoms_dict: Dictionary mapping symptoms to indices.
    - diseases_list: Dictionary mapping indices to diseases.
    - model: Trained classification model (e.g., RandomForestClassifier or SVC).
    - X_train: Optional, training data used for the model. Required for compatibility with older scikit-learn versions.

    Returns:
    - Predicted disease (str) or an error message.
    """
    try:
        # Determine input vector size
        if hasattr(model, 'n_features_in_'):
            input_vector_size = model.n_features_in_
        elif X_train is not None:
            input_vector_size = X_train.shape[1]
        else:
            raise ValueError("Model input size could not be determined. Provide X_train.")

        # Initialize input vector
        input_vector = np.zeros(input_vector_size)

        # Map symptoms to input vector
        for symptom in patient_symptoms:
            if symptom in symptoms_dict:
                symptom_index = symptoms_dict[symptom]
                if symptom_index < len(input_vector):
                    input_vector[symptom_index] = 1
                else:
                    print(f"Warning: Symptom index {symptom_index} is out of bounds.")
            else:
                print(f"Warning: Symptom '{symptom}' not recognized.")

        # Predict the disease
        predicted_index = model.predict([input_vector])[0]
        return diseases_list.get(predicted_index, "Unknown Disease")
    except Exception as e:
        print(f"Error during prediction: {e}")
        return "Prediction Failed"

In [54]:
# Load model
try:
    rf = joblib.load('models/random_forest_model.pkl')
except FileNotFoundError:
    raise FileNotFoundError("Random Forest model file not found. Ensure 'random_forest_model.pkl' is in the 'models' directory.")

# Function to test and display predictions for given indices
def test_model(model, X_test, y_test, test_indices):
    """
    Test and display predictions for specific indices.

    Parameters:
    - model: Trained model for predictions.
    - X_test: Test feature set (pandas DataFrame or NumPy array).
    - y_test: Test labels (pandas Series or NumPy array).
    - test_indices: List of indices to test.

    Returns:
    - None
    """
    if X_test is None or y_test is None:
        print("Error: X_test and y_test must be provided.")
        return

    for idx in test_indices:
        if idx >= len(X_test):
            print(f"Index {idx} is out of range. Skipping.")
            continue
        # Handle data type and reshape for prediction
        X_sample = X_test.iloc[idx].values.reshape(1, -1) if hasattr(X_test, 'iloc') else X_test[idx].reshape(1, -1)
        predicted = model.predict(X_sample)[0]
        actual = y_test[idx] if isinstance(y_test, np.ndarray) else y_test.iloc[idx]
        print(f"Test {idx + 1}:")
        print(f"  Predicted Disease: {predicted}")
        print(f"  Actual Disease: {actual}")
        print("-" * 40)

# Example: Test the Random Forest model
test_indices_rf = [0, 100]  # Replace with indices from your dataset
print("Random Forest Predictions:")
test_model(rf, X_test, y_test, test_indices_rf)

# Load datasets
sym_des = pd.read_csv("datasets/symtoms_df.csv")
precautions = pd.read_csv("datasets/precautions_df.csv")
workout = pd.read_csv("datasets/workout_df.csv")
description = pd.read_csv("datasets/description.csv")
medications = pd.read_csv("datasets/medications.csv")
diets = pd.read_csv("datasets/diets.csv")

# Helper Function
def helper(dis, description, precautions, medications, diets, workout):
    try:
        desc = description[description['Disease'] == dis]['Description']
        desc = " ".join(desc.tolist())
        pre = precautions[precautions['Disease'] == dis][['Precaution_1', 'Precaution_2', 'Precaution_3', 'Precaution_4']]
        pre = pre.values.flatten().tolist()
        med = medications[medications['Disease'] == dis]['Medication'].tolist()
        diet = diets[diets['Disease'] == dis]['Diet'].tolist()
        wrkout = workout[workout['disease'] == dis]['workout'].tolist()
        return desc, pre, med, diet, wrkout
    except Exception as e:
        print(f"Error retrieving details for disease '{dis}': {e}")
        return None, None, None, None, None

# Prediction Function
def get_predicted_disease(patient_symptoms, symptoms_dict, diseases_list, model, X_train=None):
    """
    Predict the disease based on patient symptoms using the trained model.

    Parameters:
    - patient_symptoms: List of symptoms provided by the patient.
    - symptoms_dict: Dictionary mapping symptoms to indices.
    - diseases_list: Dictionary mapping indices to diseases.
    - model: Trained classification model (e.g., RandomForestClassifier or SVC).
    - X_train: Optional, training data used for the model. Required for compatibility with older scikit-learn versions.

    Returns:
    - Predicted disease (str) or an error message.
    """
    try:
        # Determine input vector size
        if hasattr(model, 'n_features_in_'):
            input_vector_size = model.n_features_in_
        elif X_train is not None:
            input_vector_size = X_train.shape[1]
        else:
            raise ValueError("Model input size could not be determined. Provide X_train.")

        # Initialize input vector
        input_vector = np.zeros(input_vector_size)

        # Map symptoms to input vector
        for symptom in patient_symptoms:
            if symptom in symptoms_dict:
                symptom_index = symptoms_dict[symptom]
                if symptom_index < len(input_vector):
                    input_vector[symptom_index] = 1
                else:
                    print(f"Warning: Symptom index {symptom_index} is out of bounds.")
            else:
                print(f"Warning: Symptom '{symptom}' not recognized.")

        # Predict the disease
        predicted_index = model.predict([input_vector])[0]
        return diseases_list.get(predicted_index, "Unknown Disease")
    except Exception as e:
        print(f"Error during prediction: {e}")
        return "Prediction Failed"

# Symptom dictionary
symptoms_dict = {
    'itching': 0,
    'skin_rash': 1,
    'nodal_skin_eruptions': 2,
    'continuous_sneezing': 3,
    'shivering': 4,
    'chills': 5,
    'joint_pain': 6,
    'stomach_pain': 7,
    'acidity': 8,
    'ulcers_on_tongue': 9,
    'muscle_wasting': 10,
    'vomiting': 11,
    'burning_micturition': 12,
    'spotting_urination': 13,
    'fatigue': 14,
    'weight_gain': 15,
    'anxiety': 16,
    'cold_hands_and_feets': 17,
    'mood_swings': 18,
    'weight_loss': 19,
    'restlessness': 20,
    'lethargy': 21,
    'patches_in_throat': 22,
    'irregular_sugar_level': 23,
    'cough': 24,
    'high_fever': 25,
    'sunken_eyes': 26,
    'breathlessness': 27,
    'sweating': 28,
    'dehydration': 29,
    'indigestion': 30,
    'headache': 31,
    'yellowish_skin': 32,
    'dark_urine': 33,
    'nausea': 34,
    'loss_of_appetite': 35,
    'pain_behind_the_eyes': 36,
    'back_pain': 37,
    'constipation': 38,
    'abdominal_pain': 39,
    'diarrhoea': 40,
    'mild_fever': 41,
    'yellow_urine': 42,
    'yellowing_of_eyes': 43,
    'acute_liver_failure': 44,
    'fluid_overload': 45,
    'swelling_of_stomach': 46,
    'swelled_lymph_nodes': 47,
    'malaise': 48,
    'blurred_and_distorted_vision': 49,
    'phlegm': 50,
    'throat_irritation': 51,
    'redness_of_eyes': 52,
    'sinus_pressure': 53,
    'runny_nose': 54,
    'congestion': 55,
    'chest_pain': 56,
    'weakness_in_limbs': 57,
    'fast_heart_rate': 58,
    'pain_during_bowel_movements': 59,
    'pain_in_anal_region': 60,
    'bloody_stool': 61,
    'irritation_in_anus': 62,
    'neck_pain': 63,
    'dizziness': 64,
    'cramps': 65,
    'bruising': 66,
    'obesity': 67,
    'swollen_legs': 68,
    'swollen_blood_vessels': 69,
    'puffy_face_and_eyes': 70,
    'enlarged_thyroid': 71,
    'brittle_nails': 72,
    'swollen_extremities': 73,
    'excessive_hunger': 74,
    'extra_marital_contacts': 75,
    'drying_and_tingling_lips': 76,
    'slurred_speech': 77,
    'knee_pain': 78,
    'hip_joint_pain': 79,
    'muscle_weakness': 80,
    'stiff_neck': 81,
    'swelling_joints': 82,
    'movement_stiffness': 83,
    'spinning_movements': 84,
    'loss_of_balance': 85,
    'unsteadiness': 86,
    'weakness_of_one_body_side': 87,
    'loss_of_smell': 88,
    'bladder_discomfort': 89,
    'foul_smell_of_urine': 90,
    'continuous_feel_of_urine': 91,
    'passage_of_gases': 92,
    'internal_itching': 93,
    'toxic_look_typhos': 94,
    'depression': 95,
    'irritability': 96,
    'muscle_pain': 97,
    'altered_sensorium': 98,
    'red_spots_over_body': 99,
    'belly_pain': 100,
    'abnormal_menstruation': 101,
    'dischromic_patches': 102,
    'watering_from_eyes': 103,
    'increased_appetite': 104,
    'polyuria': 105,
    'family_history': 106,
    'mucoid_sputum': 107,
    'rusty_sputum': 108,
    'lack_of_concentration': 109,
    'visual_disturbances': 110,
    'receiving_blood_transfusion': 111,
    'receiving_unsterile_injections': 112,
    'coma': 113,
    'stomach_bleeding': 114,
    'distention_of_abdomen': 115,
    'history_of_alcohol_consumption': 116,
    'fluid_overload.1': 117,
    'blood_in_sputum': 118,
    'prominent_veins_on_calf': 119,
    'palpitations': 120,
    'painful_walking': 121,
    'pus_filled_pimples': 122,
    'blackheads': 123,
    'scurring': 124,
    'skin_peeling': 125,
    'silver_like_dusting': 126,
    'small_dents_in_nails': 127,
    'inflammatory_nails': 128,
    'blister': 129,
    'red_sore_around_nose': 130,
    'yellow_crust_ooze': 131
}

diseases_list = {
    0: '(vertigo) Paroymsal Positional Vertigo',
    1: 'AIDS',
    2: 'Acne',
    3: 'Alcoholic hepatitis',
    4: 'Allergy',
    5: 'Arthritis',
    6: 'Bronchial Asthma',
    7: 'Cervical spondylosis',
    8: 'Chicken pox',
    9: 'Chronic cholestasis',
    10: 'Common Cold',
    11: 'Dengue',
    12: 'Diabetes ',
    13: 'Dimorphic hemmorhoids(piles)',
    14: 'Drug Reaction',
    15: 'Fungal infection',
    16: 'GERD',
    17: 'Gastroenteritis',
    18: 'Heart attack',
    19: 'Hepatitis B',
    20: 'Hepatitis C',
    21: 'Hepatitis D',
    22: 'Hepatitis E',
    23: 'Hypertension ',
    24: 'Hyperthyroidism',
    25: 'Hypoglycemia',
    26: 'Hypothyroidism',
    27: 'Impetigo',
    28: 'Jaundice',
    29: 'Malaria',
    30: 'Migraine',
    31: 'Osteoarthritis',
    32: 'Paralysis (brain hemorrhage)',
    33: 'Peptic ulcer disease',
    34: 'Pneumonia',
    35: 'Psoriasis',
    36: 'Tuberculosis',
    37: 'Typhoid',
    38: 'Urinary tract infection',
    39: 'Varicose veins',
    40: 'hepatitis A'
}
# Patient symptoms
patient_symptoms = ['itching', 'skin_rash', 'nodal_skin_eruptions', 'dischromic _patches']

# Predict disease using Random Forest
predicted_disease = get_predicted_disease(patient_symptoms, symptoms_dict, diseases_list, rf, X_train=X_train)

# Retrieve details
desc, pre, med, diet, wrkout = helper(predicted_disease, description, precautions, medications, diets, workout)

# Display output
print(f"Predicted Disease: {predicted_disease}")
print(f"Description: {desc}")
print(f"Precautions: {pre}")
print(f"Medications: {med}")
print(f"Diet: {diet}")
print(f"Workout: {wrkout}")

Random Forest Predictions:
Test 1:
  Predicted Disease: 40
  Actual Disease: 40
----------------------------------------
Test 101:
  Predicted Disease: 39
  Actual Disease: 39
----------------------------------------
Predicted Disease: Fungal infection
Description: Fungal infection is a common skin condition caused by fungi.
Precautions: ['bath twice', 'use detol or neem in bathing water', 'keep infected area dry', 'use clean cloths']
Medications: ["['Antifungal Cream', 'Fluconazole', 'Terbinafine', 'Clotrimazole', 'Ketoconazole']"]
Diet: ["['Antifungal Diet', 'Probiotics', 'Garlic', 'Coconut oil', 'Turmeric']"]
Workout: ['Avoid sugary foods', 'Consume probiotics', 'Increase intake of garlic', 'Include yogurt in diet', 'Limit processed foods', 'Stay hydrated', 'Consume green tea', 'Eat foods rich in zinc', 'Include turmeric in diet', 'Eat fruits and vegetables']


C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


In [55]:
# let's use pycharm flask app
# but install this version in pycharm
import sklearn
print(sklearn.__version__)


1.5.2
